import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Linktree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[conic-gradient(var(--tw-gradient-stops))] from-slate-900 via-green-800 to-purple-900 min-h-full`}
      >
        {children}
      </body>
    </html>
  );
}
